import {Platform} from 'react-native'
import type {Theme} from './ThemeContext'
import {colors} from './styles'

export const defaultTheme: Theme = {
  colorScheme: 'light',
  palette: {
    default: {
      background: colors.white,
      backgroundLight: colors.gray1,
      text: colors.black,
      textLight: colors.gray5,
      textInverted: colors.white,
      link: colors.blue3,
      border: '#f0e9e9',
      borderDark: '#e0d9d9',
      icon: colors.gray4,

      // non-standard
      textVeryLight: colors.gray4,
      replyLine: colors.gray2,
      replyLineDot: colors.gray3,
      unreadNotifBg: '#ebf6ff',
      unreadNotifBorder: colors.blue1,
      postCtrl: '#71768A',
      brandText: '#0066FF',
      emptyStateIcon: '#B6B6C9',
    },
    primary: {
      background: colors.blue3,
      backgroundLight: colors.blue2,
      text: colors.white,
      textLight: colors.blue0,
      textInverted: colors.blue3,
      link: colors.blue0,
      border: colors.blue4,
      borderDark: colors.blue5,
      icon: colors.blue4,
    },
    secondary: {
      background: colors.green3,
      backgroundLight: colors.green2,
      text: colors.white,
      textLight: colors.green1,
      textInverted: colors.green4,
      link: colors.green1,
      border: colors.green4,
      borderDark: colors.green5,
      icon: colors.green4,
    },
    inverted: {
      background: colors.black,
      backgroundLight: colors.gray6,
      text: colors.white,
      textLight: colors.gray3,
      textInverted: colors.black,
      link: colors.blue2,
      border: colors.gray3,
      borderDark: colors.gray2,
      icon: colors.gray5,
    },
    error: {
      background: colors.red3,
      backgroundLight: colors.red2,
      text: colors.white,
      textLight: colors.red1,
      textInverted: colors.red3,
      link: colors.red1,
      border: colors.red4,
      borderDark: colors.red5,
      icon: colors.red4,
    },
  },
  shapes: {
    button: {
      // TODO
    },
    bigButton: {
      // TODO
    },
    smallButton: {
      // TODO
    },
  },
  typography: {
    '2xl-thin': {
      fontSize: 18,
      letterSpacing: 0.25,
      fontWeight: '300',
    },
    '2xl': {
      fontSize: 18,
      letterSpacing: 0.25,
      fontWeight: '400',
    },
    '2xl-medium': {
      fontSize: 18,
      letterSpacing: 0.25,
      fontWeight: '500',
    },
    '2xl-bold': {
      fontSize: 18,
      letterSpacing: 0.25,
      fontWeight: '700',
    },
    '2xl-heavy': {
      fontSize: 18,
      letterSpacing: 0.25,
      fontWeight: '800',
    },
    'xl-thin': {
      fontSize: 17,
      letterSpacing: 0.25,
      fontWeight: '300',
    },
    xl: {
      fontSize: 17,
      letterSpacing: 0.25,
      fontWeight: '400',
    },
    'xl-medium': {
      fontSize: 17,
      letterSpacing: 0.25,
      fontWeight: '500',
    },
    'xl-bold': {
      fontSize: 17,
      letterSpacing: 0.25,
      fontWeight: '700',
    },
    'xl-heavy': {
      fontSize: 17,
      letterSpacing: 0.25,
      fontWeight: '800',
    },
    'lg-thin': {
      fontSize: 16,
      letterSpacing: 0.25,
      fontWeight: '300',
    },
    lg: {
      fontSize: 16,
      letterSpacing: 0.25,
      fontWeight: '400',
    },
    'lg-medium': {
      fontSize: 16,
      letterSpacing: 0.25,
      fontWeight: '500',
    },
    'lg-bold': {
      fontSize: 16,
      letterSpacing: 0.25,
      fontWeight: '700',
    },
    'lg-heavy': {
      fontSize: 16,
      letterSpacing: 0.25,
      fontWeight: '800',
    },
    'md-thin': {
      fontSize: 15,
      letterSpacing: 0.25,
      fontWeight: '300',
    },
    md: {
      fontSize: 15,
      letterSpacing: 0.25,
      fontWeight: '400',
    },
    'md-medium': {
      fontSize: 15,
      letterSpacing: 0.25,
      fontWeight: '500',
    },
    'md-bold': {
      fontSize: 15,
      letterSpacing: 0.25,
      fontWeight: '700',
    },
    'md-heavy': {
      fontSize: 15,
      letterSpacing: 0.25,
      fontWeight: '800',
    },
    'sm-thin': {
      fontSize: 14,
      letterSpacing: 0.25,
      fontWeight: '300',
    },
    sm: {
      fontSize: 14,
      letterSpacing: 0.25,
      fontWeight: '400',
    },
    'sm-medium': {
      fontSize: 14,
      letterSpacing: 0.25,
      fontWeight: '500',
    },
    'sm-bold': {
      fontSize: 14,
      letterSpacing: 0.25,
      fontWeight: '700',
    },
    'sm-heavy': {
      fontSize: 14,
      letterSpacing: 0.25,
      fontWeight: '800',
    },
    'xs-thin': {
      fontSize: 13,
      letterSpacing: 0.25,
      fontWeight: '300',
    },
    xs: {
      fontSize: 13,
      letterSpacing: 0.25,
      fontWeight: '400',
    },
    'xs-medium': {
      fontSize: 13,
      letterSpacing: 0.25,
      fontWeight: '500',
    },
    'xs-bold': {
      fontSize: 13,
      letterSpacing: 0.25,
      fontWeight: '700',
    },
    'xs-heavy': {
      fontSize: 13,
      letterSpacing: 0.25,
      fontWeight: '800',
    },

    'title-2xl': {
      fontSize: 34,
      letterSpacing: 0.25,
      fontWeight: '500',
    },
    'title-xl': {
      fontSize: 28,
      letterSpacing: 0.25,
      fontWeight: '500',
    },
    'title-lg': {
      fontSize: 22,
      fontWeight: '500',
    },
    title: {
      fontWeight: '500',
      fontSize: 20,
      letterSpacing: 0.15,
    },
    'title-sm': {
      fontWeight: 'bold',
      fontSize: 17,
      letterSpacing: 0.15,
    },
    'post-text': {
      fontSize: 16,
      letterSpacing: 0.2,
      fontWeight: '400',
    },
    'post-text-lg': {
      fontSize: 22,
      letterSpacing: 0.4,
      fontWeight: '400',
    },
    'button-lg': {
      fontWeight: '500',
      fontSize: 18,
      letterSpacing: 0.5,
    },
    button: {
      fontWeight: '500',
      fontSize: 14,
      letterSpacing: 0.5,
    },
    mono: {
      fontSize: 14,
      fontFamily: Platform.OS === 'android' ? 'monospace' : 'Courier New',
    },
  },
}

export const darkTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: colors.black,
      backgroundLight: colors.gray7,
      text: colors.white,
      textLight: colors.gray3,
      textInverted: colors.black,
      link: colors.blue3,
      border: colors.gray7,
      borderDark: colors.gray6,
      icon: colors.gray4,

      // non-standard
      textVeryLight: colors.gray4,
      replyLine: colors.gray5,
      replyLineDot: colors.gray6,
      unreadNotifBg: colors.blue7,
      unreadNotifBorder: colors.blue6,
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: colors.gray4,
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: colors.blue2,
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: colors.green2,
    },
    inverted: {
      background: colors.white,
      backgroundLight: colors.gray2,
      text: colors.black,
      textLight: colors.gray5,
      textInverted: colors.white,
      link: colors.blue3,
      border: colors.gray3,
      borderDark: colors.gray4,
      icon: colors.gray1,
    },
  },
}

export const slateTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#64748b',
      backgroundLight: '#475569',
      text: '#ffffff',
      textLight: '#334155',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#475569',
      borderDark: '#334155',
      icon: '#475569',
      textVeryLight: '#475569',
      replyLine: '#334155',
      replyLineDot: '#475569',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#475569',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const grayTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#6b7280',
      backgroundLight: '#4b5563',
      text: '#ffffff',
      textLight: '#374151',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#4b5563',
      borderDark: '#374151',
      icon: '#4b5563',
      textVeryLight: '#4b5563',
      replyLine: '#374151',
      replyLineDot: '#4b5563',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#4b5563',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const zincTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#71717a',
      backgroundLight: '#52525b',
      text: '#ffffff',
      textLight: '#404040',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#52525b',
      borderDark: '#404040',
      icon: '#52525b',
      textVeryLight: '#52525b',
      replyLine: '#404040',
      replyLineDot: '#52525b',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#52525b',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const neutralTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#737373',
      backgroundLight: '#525252',
      text: '#ffffff',
      textLight: '#404040',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#525252',
      borderDark: '#404040',
      icon: '#525252',
      textVeryLight: '#525252',
      replyLine: '#404040',
      replyLineDot: '#525252',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#525252',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const stoneTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#78716c',
      backgroundLight: '#57534e',
      text: '#ffffff',
      textLight: '#44403c',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#57534e',
      borderDark: '#44403c',
      icon: '#57534e',
      textVeryLight: '#57534e',
      replyLine: '#44403c',
      replyLineDot: '#57534e',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#57534e',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const redTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#ef4444',
      backgroundLight: '#dc2626',
      text: '#ffffff',
      textLight: '#b91c1c',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#dc2626',
      borderDark: '#b91c1c',
      icon: '#dc2626',
      textVeryLight: '#dc2626',
      replyLine: '#b91c1c',
      replyLineDot: '#dc2626',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#dc2626',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const orangeTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#fb923c',
      backgroundLight: '#ea580c',
      text: '#ffffff',
      textLight: '#c2410c',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#ea580c',
      borderDark: '#c2410c',
      icon: '#ea580c',
      textVeryLight: '#ea580c',
      replyLine: '#c2410c',
      replyLineDot: '#ea580c',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#ea580c',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const amberTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#fbbf24',
      backgroundLight: '#f59e0b',
      text: '#ffffff',
      textLight: '#b45309',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#f59e0b',
      borderDark: '#b45309',
      icon: '#f59e0b',
      textVeryLight: '#f59e0b',
      replyLine: '#b45309',
      replyLineDot: '#f59e0b',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#f59e0b',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const yellowTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#facc15',
      backgroundLight: '#eab308',
      text: '#ffffff',
      textLight: '#a16207',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#eab308',
      borderDark: '#a16207',
      icon: '#eab308',
      textVeryLight: '#eab308',
      replyLine: '#a16207',
      replyLineDot: '#eab308',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#eab308',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const limeTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#a3e635',
      backgroundLight: '#84cc16',
      text: '#ffffff',
      textLight: '#4d7c0f',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#84cc16',
      borderDark: '#4d7c0f',
      icon: '#84cc16',
      textVeryLight: '#84cc16',
      replyLine: '#4d7c0f',
      replyLineDot: '#84cc16',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#84cc16',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const greenTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#4ade80',
      backgroundLight: '#22c55e',
      text: '#ffffff',
      textLight: '#15803d',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#22c55e',
      borderDark: '#15803d',
      icon: '#22c55e',
      textVeryLight: '#22c55e',
      replyLine: '#15803d',
      replyLineDot: '#22c55e',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#22c55e',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const emeraldTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#34d399',
      backgroundLight: '#10b981',
      text: '#ffffff',
      textLight: '#059669',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#10b981',
      borderDark: '#059669',
      icon: '#10b981',
      textVeryLight: '#10b981',
      replyLine: '#059669',
      replyLineDot: '#10b981',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#10b981',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const tealTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#2dd4bf',
      backgroundLight: '#14b8a6',
      text: '#ffffff',
      textLight: '#0f766e',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#14b8a6',
      borderDark: '#0f766e',
      icon: '#14b8a6',
      textVeryLight: '#14b8a6',
      replyLine: '#0f766e',
      replyLineDot: '#14b8a6',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#14b8a6',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const cyanTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#22d3ee',
      backgroundLight: '#06b6d4',
      text: '#ffffff',
      textLight: '#0891b2',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#06b6d4',
      borderDark: '#0891b2',
      icon: '#06b6d4',
      textVeryLight: '#06b6d4',
      replyLine: '#0891b2',
      replyLineDot: '#06b6d4',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#06b6d4',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const skyTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#38bdf8',
      backgroundLight: '#0ea5e9',
      text: '#ffffff',
      textLight: '#0369a1',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#0ea5e9',
      borderDark: '#0369a1',
      icon: '#0ea5e9',
      textVeryLight: '#0ea5e9',
      replyLine: '#0369a1',
      replyLineDot: '#0ea5e9',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#0ea5e9',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const blueTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#60a5fa',
      backgroundLight: '#3b82f6',
      text: '#ffffff',
      textLight: '#1d4ed8',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#3b82f6',
      borderDark: '#1d4ed8',
      icon: '#3b82f6',
      textVeryLight: '#3b82f6',
      replyLine: '#1d4ed8',
      replyLineDot: '#3b82f6',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#3b82f6',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const indigoTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#818cf8',
      backgroundLight: '#6366f1',
      text: '#ffffff',
      textLight: '#4338ca',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#6366f1',
      borderDark: '#4338ca',
      icon: '#6366f1',
      textVeryLight: '#6366f1',
      replyLine: '#4338ca',
      replyLineDot: '#6366f1',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#6366f1',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const violetTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#a78bfa',
      backgroundLight: '#8b5cf6',
      text: '#ffffff',
      textLight: '#6d28d9',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#8b5cf6',
      borderDark: '#6d28d9',
      icon: '#8b5cf6',
      textVeryLight: '#8b5cf6',
      replyLine: '#6d28d9',
      replyLineDot: '#8b5cf6',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#8b5cf6',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const purpleTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#c084fc',
      backgroundLight: '#a855f7',
      text: '#ffffff',
      textLight: '#7e22ce',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#a855f7',
      borderDark: '#7e22ce',
      icon: '#a855f7',
      textVeryLight: '#a855f7',
      replyLine: '#7e22ce',
      replyLineDot: '#a855f7',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#a855f7',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const fuchsiaTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#e879f9',
      backgroundLight: '#d946ef',
      text: '#ffffff',
      textLight: '#a21caf',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#d946ef',
      borderDark: '#a21caf',
      icon: '#d946ef',
      textVeryLight: '#d946ef',
      replyLine: '#a21caf',
      replyLineDot: '#d946ef',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#d946ef',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}

export const pinkTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#fb7185',
      backgroundLight: '#f43f5e',
      text: '#ffffff',
      textLight: '#be185d',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#f43f5e',
      borderDark: '#be185d',
      icon: '#f43f5e',
      textVeryLight: '#f43f5e',
      replyLine: '#be185d',
      replyLineDot: '#f43f5e',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#f43f5e',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}
export const roseTheme: Theme = {
  ...defaultTheme,
  colorScheme: 'dark',
  palette: {
    ...defaultTheme.palette,
    default: {
      background: '#fb7185',
      backgroundLight: '#f43f5e',
      text: '#ffffff',
      textLight: '#be123c',
      textInverted: '#000000',
      link: '#3b82f6',
      border: '#f43f5e',
      borderDark: '#be123c',
      icon: '#f43f5e',
      textVeryLight: '#f43f5e',
      replyLine: '#be123c',
      replyLineDot: '#f43f5e',
      unreadNotifBg: '#0ea5e9',
      unreadNotifBorder: '#38bdf8',
      postCtrl: '#707489',
      brandText: '#0085ff',
      emptyStateIcon: '#f43f5e',
    },
    primary: {
      ...defaultTheme.palette.primary,
      textInverted: '#dbeafe',
    },
    secondary: {
      ...defaultTheme.palette.secondary,
      textInverted: '#86efac',
    },
    inverted: {
      background: '#ffffff',
      backgroundLight: '#e5e5e5',
      text: '#000000',
      textLight: '#737373',
      textInverted: '#ffffff',
      link: '#3b82f6',
      border: '#d4d4d4',
      borderDark: '#a3a3a3',
      icon: '#525252',
    },
  },
}
